# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'core.archive',
        'core.compressor_core',
        'core.file_utils',
        'core.rsf_wrapper',
        'worker',
        'flet_app',
        'numba',
        'numpy',
        'numpy._core',
        'numpy._core.overrides',
        'pydicom',
        'pydicom.config',
        'pydicom.dataelem',
        'pathlib',
        'tempfile',
        'threading',
        'time',
        'traceback',
        'platform',
        'logging',
        'os',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[
        'pyi_rth_multiprocessing.py',
        'pyi_rth_pkgutil.py',
    ],
    excludes=[
        'tkinter', 'tcl', 'tk', 'distutils', 'setuptools', 'site', 'pydoc',
        'matplotlib', 'scipy', 'pandas', 'jupyter', 'ipython', 'notebook',
        'IPython', 'ipykernel', 'qtpy', 'pyqt5', 'pyqt6', 'pyside2', 'pyside6',
        'wx', 'kivy', 'pygame', 'flask', 'django', 'fastapi', 'uvicorn',
        'requests', 'urllib3', 'chardet', 'certifi', 'idna', 'cryptography',
        'OpenSSL', 'paramiko', 'fabric', 'ansible', 'docker', 'kubernetes',
        'tensorflow', 'torch', 'torchvision', 'transformers', 'datasets',
        'scikit-learn', 'xgboost', 'lightgbm', 'catboost', 'optuna',
        'mlflow', 'wandb', 'tensorboard', 'plotly', 'seaborn', 'bokeh',
        'streamlit', 'gradio', 'dash', 'panel', 'holoviews', 'hvplot',
        'altair', 'vega_datasets', 'folium', 'geopandas', 'shapely',
        'rasterio', 'xarray', 'dask', 'distributed', 'ray', 'modin',
        'vaex', 'polars', 'duckdb', 'sqlalchemy', 'psycopg2', 'pymysql',
        'pymongo', 'redis', 'celery', 'rq', 'airflow', 'prefect',
        'pytest', 'unittest', 'nose', 'coverage', 'black', 'isort',
        'flake8', 'mypy', 'pylint', 'bandit', 'safety', 'pip-tools',
        'poetry', 'pipenv', 'conda', 'mamba', 'micromamba',
        'PIL.ImageQt', 'PIL.ImageTk', 'PIL.TkPhotoImage',
    ],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='RSFCompressor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
